{
 "title": "C-Chain",
 "tags": [ "Metal" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Accepted Blocks in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(metal_snowman_blks_accepted_count{chain=\"C\", job=\"metalgo\"}[1m]))>0",
     "legendFormat": "Blocks {{node_id}}"
    }
   ]
  },
  {
   "title": "Rejected Blocks in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(metal_snowman_blks_rejected_count{chain=\"C\", job=\"metalgo\"}[1m]))>0",
     "legendFormat": "Blocks {{node_id}}"
    }
   ]
  },
  {
   "title": "Average Block Acceptance Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and acceptance by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(metal_snowman_blks_accepted_sum{chain=\"C\", job=\"metalgo\"}[5m]) / rate(metal_snowman_blks_accepted_count{chain=\"C\", job=\"metalgo\"}[5m])",
     "legendFormat": "Avg Acceptance Latency {{node_id}}"
    }
   ]
  },
  {
   "title": "Average Block Rejection Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and rejection by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(metal_snowman_blks_rejected_sum{chain=\"C\", job=\"metalgo\"}[5m]) / rate(metal_snowman_blks_rejected_count{chain=\"C\", job=\"metalgo\"}[5m])",
     "legendFormat": "Avg Rejection Latency {{node_id}}"
    }
   ]
  },
  {
   "title": "Processing Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "metal_snowman_blks_processing{chain=\"C\", job=\"metalgo\"}>0",
     "legendFormat": "Blocks {{node_id}}"
    }
   ]
  },
  {
   "title": "Incomplete Polls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "metal_snowman_polls{chain=\"C\"} > 0",
     "legendFormat": "Polls {{node_id}}"
    }
   ]
  },
  {
   "title": "Message Handling Time (Total)",
   "type": "timeseries",
   "description": "Measures how much of each second is being spent handling different kinds of messages on the C-Chain.\nThe value for chits, for example, is the number of seconds spent handling chits messages per second, over the last 30 seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(metal_handler_message_handling_time{chain=\"C\", job=\"metalgo\"}[5m])",
     "legendFormat": "{{ op }} {{node_id}}"
    }
   ]
  },
  {
   "title": "Percentage of Successful Queries",
   "type": "timeseries",
   "description": "Percentage of queries for which we receive chits on time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "($A + 1) / ($A + $B + 1)", "type": "math" }
   ]
  },
  {
   "title": "Message Handling Time (per Message)",
   "type": "timeseries",
   "description": "Measures how long each kind of request on the C-Chain takes to handle.\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(metal_handler_message_handling_time{chain=\"C\", job=\"metalgo\"}[5m])/rate(metal_handler_messages{chain=\"C\", job=\"metalgo\"}[5m])",
     "legendFormat": "{{ op }} {{node_id}}"
    }
   ]
  },
  {
   "title": "Unprocessed Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "metal_handler_sync_unprocessed_msgs_count{chain=\"C\"}",
     "legendFormat": "{{ op }} {{node_id}}"
    },
    {
     "expr": "metal_handler_async_unprocessed_msgs_count{chain=\"C\"}",
     "legendFormat": "{{ op }}"
    }
   ]
  },
  {
   "title": "Incoming Messages Expired in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(metal_handler_expired{chain=\"C\", job=\"metalgo\"}[1m]) or 0 * up",
     "legendFormat": "{{ op }} {{node_id}}"
    }
   ]
  },
  {
   "title": "AVAX Benched",
   "type": "timeseries",
   "description": "The total stake of validators currently \"benched\" due to poor query responsiveness. Queries to these validators will immediately timeout until they are removed from the \"bench.\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(metal_benchlist_benched_weight{chain=\"C\", job=\"metalgo\"}[15m]) / 10^9",
     "legendFormat": "AVAX Benched {{node_id}}"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "Measures how many of each kind of message are received per second on the C-Chain.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(metal_handler_messages{chain=\"C\", job=\"metalgo\"}[5m])",
     "legendFormat": "{{ op }} {{node_id}}"
    }
   ]
  },
  {
   "title": "Block ID Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the cache where the key is the byte representation of the block, and the value is the block's ID",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "type": "math", "expression": "$A/$B" }
   ]
  },
  {
   "title": "Decided Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the decided block cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "type": "math", "expression": "$A/$B" }
   ]
  },
  {
   "title": "Missing Block Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the missing block cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "type": "math", "expression": "$A/$B" }
   ]
  },
  {
   "title": "Unverified Block Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the unverified block cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "type": "math", "expression": "$A/$B" }
   ]
  }
 ]
}